#! /bin/sh
### BEGIN INIT INFO
# Provides:         keylist, serialcom,... 
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         
# Short-Description: start all things custom for lazzzorauth 
# Description:
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions


case "$1" in
  start)

	echo "Setting firewall" >&2
	/sbin/iptables -A PREROUTING -t nat -i eth0 -p tcp -m tcp --dport 515 -j DNAT --to-destination 10.254.253.2:515

        echo "Setting time" >&2
        /usr/sbin/ntpdate-debian > /dev/null &
        

        echo "Starting to fetch keylist from server" >&2
        /root/lazzzorauth/bin/get_keylist.sh&




echo 1 >  /proc/sys/net/ipv4/ip_forward; 

### ENABLE THIS!
        echo "Starting serial communication with arduino" >&2
	cd /root/lazzzorauth/nodejs/; /usr/bin/node /root/lazzzorauth/nodejs/lazzzorauth.js&




	;;
  restart|reload|force-reload|stop)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  *)
	echo "Usage: $0 start" >&2
	exit 3
	;;
esac

:
